### ISSUE TITLE
"Using Juju Storage" openstack/cinder example doesn't work

### ISSUE THREAD

**Issue by fginther** [juju/docs#1553]
From "https://jujucharms.com/docs/stable/charms-storage" is the example for deploying a charm with storage:

`juju deploy cs:~axwalk/postgresql --storage data=10G`

This does not work for me, I see this in the unit log:

```
2016-12-01 20:52:50 INFO data-storage-attached Traceback (most recent call last):
2016-12-01 20:52:50 INFO data-storage-attached   File "/var/lib/juju/agents/unit-postgresql-0/charm/hooks/data-storage-attached", line 2671, in <module>
2016-12-01 20:52:50 INFO data-storage-attached     hooks.execute(sys.argv)
2016-12-01 20:52:50 INFO data-storage-attached   File "/var/lib/juju/agents/unit-postgresql-0/charm/hooks/charmhelpers/core/hookenv.py", line 490, in execute
2016-12-01 20:52:50 INFO data-storage-attached     self._hooks[hook_name]()
2016-12-01 20:52:50 INFO data-storage-attached   File "/var/lib/juju/agents/unit-postgresql-0/charm/hooks/data-storage-attached", line 2609, in data_storage_attached
2016-12-01 20:52:50 INFO data-storage-attached     config_changed(mount_point=external_volume_mount)
2016-12-01 20:52:50 INFO data-storage-attached   File "/var/lib/juju/agents/unit-postgresql-0/charm/hooks/data-storage-attached", line 1153, in config_changed
2016-12-01 20:52:50 INFO data-storage-attached     if local_state['state'] in ('standalone', 'master'):
2016-12-01 20:52:50 INFO data-storage-attached KeyError: 'state'
2016-12-01 20:52:50 ERROR juju.worker.uniter.operation runhook.go:107 hook "data-storage-attached" failed: exit status 1
```

**Comment by axw** [comment]
We really need to update the example with a released charm. The current, promulgated "postgresql" supports storage now, so we could just use that.

**Comment by evilnick** [comment]
thanks @axw, we will fix it

**Comment by matthewhelmke** [comment]
https://jujucharms.com/postgresql/109
